version: "3"

services:
  mysql:
    container_name: database
    image: mysql/mysql-server:5.7
    env_file:
      - database/.env
    # Set max_allowed_packet to 256M
    command: --max_allowed_packet=32505856
    ports:
      - "3306:3306"
    volumes:
      - ./database/data:/var/lib/mysql
    networks:
      - fullstack-challenge

  frontend:
    build:
      context: "./frontend"
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    networks:
      - fullstack-challenge
  api:
    container_name: api
    image: api
    build:
      context: ./api
      dockerfile: Dockerfile
    command: ["uvicorn", "fullstack_challenge_api.main:app", "--port=20002", "--host=0.0.0.0", "--reload"]
    environment:
      COLUMNS: 164
    tty: true
    ports:
      - "20002:20002"
    env_file:
      - ./api/config/.env
    volumes:
      - ./api/fullstack_challenge_api:/fullstack_challenge_api
      - ./api/config/config.toml:/config/config.toml
    networks:
      - fullstack-challenge

networks:
  fullstack-challenge:
